// The mock harness (roster handle "demo-bot"): a real child process that
// proves the tag→spawn→CLI loop end to end with zero credentials. The host
// spawns it as `bun dev/mock-agent.ts` with the rendered thread context on
// $ELAN_CONTEXT and the elan shim dir prepended to PATH — so it drives the
// `elan` CLI as a child process, exactly the way a real harness would.
//
// Silent-success probe: answer only in the stream, never via elan —
// exercises the host's fallback post (mention text must NOT tag).
if (process.env.ELAN_MOCK_SILENT === "1") { console.log("Streamed answer only — also hi @fable-5, do not summon."); process.exit(0); }
// ELAN_MOCK_WAKE=1 flips it into wake-test mode: arm a wake and exit.

import { writeFileSync } from "node:fs";

const thread = process.env.ELAN_THREAD ?? "(unknown-thread)";
const agent = process.env.ELAN_AGENT ?? "demo-bot";
if (!process.env.ELAN_CONTEXT)
  console.error("[mock-agent] warning: no ELAN_CONTEXT on env");

function elan(...args: string[]): void {
  // Through the shim on PATH, not the .ts file directly — the loop being
  // proven includes the shim.
  const r = Bun.spawnSync(["elan", ...args], {
    stdin: "ignore",
    stdout: "inherit",
    stderr: "inherit",
  });
  if (r.exitCode !== 0) {
    console.error(`[mock-agent] \`elan ${args.join(" ")}\` exited ${r.exitCode}`);
    process.exit(1);
  }
}

// Small pauses so a human watching the board sees the steps land live.
const pause = () => Bun.sleepSync(100 + Math.random() * 200);

if (process.env.ELAN_MOCK_WAKE === "1") {
  elan("wake-me", "--on", "post");
  process.exit(0);
}

// A JSONL-ish narration line — exercises the host's tolerant stdout parser.
console.log(JSON.stringify({ type: "mock", note: `up as @${agent} in ${thread}` }));

elan("post", "Looking at this now.");
pause();

writeFileSync("mock-plan.md", `# Mock plan\n\nGenerated by ${agent} for thread ${thread}.\n`);
pause();

elan("attach", "mock-plan.md", "--note", "Plan attached.");
pause();

elan("status", "in-review");
pause();

// No @mentions here on purpose — a mention would spawn another session (loop).
elan("post", "Done — plan ready for review.");
process.exit(0);
