// The mock harness (roster handle "demo-bot"): a real child process that
// proves the tag→turn→CLI loop end to end with zero credentials. RESIDENT by
// default (the hot-session model's test double): the host spawns it as
// `bun dev/mock-agent.ts` with stdin piped, then injects one JSON line per
// turn — {"prompt": string, "turn": N} — and reads a claude-stream-shaped
// {"type":"result",…} line as the turn-end signal.
//
//   turn 1     → the full demo script (post, artifact, post), the same loop
//                the one-shot mock always drove;
//   turn N > 1 → `elan post "turn N ack: <prompt's first 40 chars>"`;
//   any turn whose PING contains "[stall]" → no result line, sleep forever
//                (the host's per-turn timeout test);
//   ELAN_MOCK_SILENT=1 → turn 1 answers ONLY in the stream (the host's
//                silent-success fallback test) — no elan calls.
//
// After each turn it blocks reading stdin for the next one; a closed stdin
// ends the process. `--oneshot` keeps the legacy behavior (script from
// $ELAN_CONTEXT, then exit) for anything driving the mock directly.

import { writeFileSync } from "node:fs";

const ONESHOT = process.argv.includes("--oneshot");
const SILENT = process.env.ELAN_MOCK_SILENT === "1";

const thread = process.env.ELAN_THREAD ?? "(unknown-thread)";
const agent = process.env.ELAN_AGENT ?? "demo-bot";

// Mirrors TURN_PING_SEPARATOR in dev/elan-host.ts: a full-context prompt ends
// with "── this turn's ping ──\n\n<the triggering post>". Only the ping may
// trigger stall mode — board history mentioning "[stall]" must not.
const PING_SEPARATOR = "── this turn's ping ──";

function pingOf(prompt: string): string {
  const idx = prompt.lastIndexOf(PING_SEPARATOR);
  return idx === -1 ? prompt : prompt.slice(idx + PING_SEPARATOR.length);
}

/** The claude-stream dialect turn-end line the host settles a turn on. */
function turnEnd(note: string): void {
  console.log(
    JSON.stringify({ type: "result", subtype: "success", is_error: false, result: note }),
  );
}

function elan(...args: string[]): void {
  // Through the shim on PATH, not the .ts file directly — the loop being
  // proven includes the shim.
  const r = Bun.spawnSync(["elan", ...args], {
    stdin: "ignore",
    stdout: "inherit",
    stderr: "inherit",
  });
  if (r.exitCode !== 0) {
    console.error(`[mock-agent] \`elan ${args.join(" ")}\` exited ${r.exitCode}`);
    process.exit(1);
  }
}

// Small pauses so a human watching the board sees the steps land live (and so
// a second ping can arrive while the first turn runs — the clone regression).
const pause = () => Bun.sleepSync(100 + Math.random() * 200);

/** The demo script — the mock's first turn. */
function runScript(): void {
  if (SILENT) {
    // Silent-success probe: answer only in the stream, never via elan —
    // exercises the host's fallback post (mention text must NOT tag).
    const answer = "Streamed answer only — also hi @fable-5, do not summon.";
    console.log(answer);
    turnEnd(answer);
    return;
  }

  // A JSONL-ish narration line — exercises the host's tolerant stdout parser.
  console.log(JSON.stringify({ type: "mock", note: `up as @${agent} in ${thread}` }));

  elan("post", "Looking at this now.");
  pause();

  writeFileSync("mock-plan.md", `# Mock plan\n\nGenerated by ${agent} for thread ${thread}.\n`);
  pause();

  elan("attach", "mock-plan.md", "--note", "Plan attached.");
  pause();

  // No @mentions here on purpose — a mention would ping another agent (loop).
  elan("post", "Done — plan ready for review.");
  turnEnd("Done — plan ready for review.");
}

if (ONESHOT) {
  if (!process.env.ELAN_CONTEXT)
    console.error("[mock-agent] warning: no ELAN_CONTEXT on env");
  runScript();
  process.exit(0);
}

// ── resident mode (default under the host) ──────────────────────────────────
let turnsSeen = 0;
for await (const line of console) {
  turnsSeen++;
  let prompt = "";
  let turnNo = turnsSeen;
  try {
    const msg = JSON.parse(line) as { prompt?: string; turn?: number };
    if (typeof msg.prompt === "string") prompt = msg.prompt;
    if (typeof msg.turn === "number") turnNo = msg.turn;
  } catch {
    prompt = line; // tolerate a bare-text turn
  }

  if (pingOf(prompt).includes("[stall]")) {
    // Stall mode: never settle the turn — the host must SIGTERM us.
    await new Promise(() => {});
  }

  if (turnNo === 1) {
    runScript();
  } else {
    const gist = prompt.slice(0, 40).replace(/\s+/g, " ").trim();
    elan("post", `turn ${turnNo} ack: ${gist}`);
    turnEnd(`turn ${turnNo} ack`);
  }
}
process.exit(0);
